# Generated by Django 5.1.2 on 2025-02-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='partidas_ganadas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='partidas_jugadas',
            field=models.FloatField(default=0),
        ),
    ]
